pipeline {
    agent any

    parameters {
        string(defaultValue: "TEST", description: "Which environment to deploy in?", name: "deployEnv")
    }
    
    stages {
        stage("demo") {
            steps {
                echo "string is set to: ${params.deployENV}"
            }
        }
    }
}
